-- out에 있는데 In에 없는것 - > left join 에서 inner join 뺌
SELECT o.ANIMAL_ID, o.NAME FROM ANIMAL_OUTS as o
WHERE o.ANIMAL_ID NOT IN (
    SELECT o.ANIMAL_ID FROM ANIMAL_OUTS as o
    INNER JOIN ANIMAL_INS ON ANIMAL_INS.ANIMAL_ID = o.ANIMAL_ID
    )
ORDER BY ANIMAL_ID